// <auto-generated />
using Barlang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barlang.Migrations
{
    [DbContext(typeof(BarlangDbContext))]
    [Migration("20250930061900_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Barlang.Models.Barlang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hossz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kiterjedes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Magassag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Melyseg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Barlang");
                });
#pragma warning restore 612, 618
        }
    }
}
